GET {{CookWizard_HostAddress}}/api/recipes/
Accept: application/json

###

GET {{CookWizard_HostAddress}}/api/recipes/13c6681f-5140-49ce-b00d-25590275d7c3
Accept: application/json

###

POST {{CookWizard_HostAddress}}/api/recipes/create
Content-Type: application/json

{
  "category": "desert",
  "name": "Test pie",
  "portions": 4,
  "preparationTime": {
    "time": 20,
    "unit": "minutes",
    "timeInSeconds": 1200
  },
  "ingredients": [
    {
      "quantity": 4,
      "unit": "leaves",
      "product": "mint",
      "preparationNotes": "desinfected"
    }
  ],
  "preparationSteps": [
    {
      "order": 1,
      "step": "blend all"
    }
  ]
}

###